In [1]:
import pandas as pd
from barcode_key_converter import *

In [2]:
codebook = pd.read_csv("../../10k_barcodes_647.csv", index_col = 0)

In [3]:
codebook

          Hyb1  Hyb2  Hyb3  Hyb4
Genes
Impact      17    16    13    20
Stxbp1      14    14     4     4
Sv2a        20     1     1    20
Mpped1       6    14     4    16
Pak3        14    19    13    20
Slc24a3     17    18     9     6
Fam126b     20    14     4    10
Sel1l       14     1     4    11
Sars         5     2     4     3
Sult4a1      8    12     4    16
Usp14       19    14     4     9
Idh3a        6    14    16     4
Pak1        13    16     9    20
Dmxl2       20    19    16     3
Usp34        2    18    16     4
Aplp2       10    16    13    13
Serinc3     16    16    10     2
Actr10       1    14     4    11
Eps15       20    16     2    14
Ctnnd2      12    20    13    19
Opcml        9     2    20    11
Metap2      20     5    10    15
Serf2       14    20    11     3
Trim9        9    10    19    20
Kcnb1       17     1    13     5
Gng3         5     9    10     4
Adcy1        2     8     4     6
Itfg1        5    20     9    16
Ap3b2        6    12    12     6
Arl8b        1    16     7    10
...        ...   ...   ...   ...
Cdcp1       11    20    13    18
Ptpn7       10    18     4     4
Nkx2-9      20     6    14    12
Msx3        10    19     8     1
Il1rn        5    16     2    19
Clcf1       13     7    12     8
Tmem30b     18    18     8     8
Six6         2     9    19    12
Myf5         4     6    14    16
Nek10       15    19    10     4
Bpifb4      15    20     3    12
Cutal       19    17    17    19
Gnat1       19    12     2     9
Myoc         4     7     4     7
Vav2        14     8     4    18
Mroh9       19     9    12    16
Cd96         9    13    10    12
Ankrd34c    16     3    18     1
Oas1b        7     7     6     8
Pkp3        12     4    19    17
Dsc1         2    16    16     2
Klhdc7b     15    10    20     5
Slc17a9     12    16    14    14
Lrrc25      12     5    13     4
Slc17a2     18    12     5     5
Slc10a6     11    20    17    14
Moxd2       15    14    10    19
Mpzl2        1     6    11    16
Gbgt1       17     9     1     5
Cd300lf      5     6    19    12

[3334 rows x 4 columns]

In [4]:
#generate possible codes
from itertools import product
ps = np.arange(1,21,1)
perm_ps = list(product(ps,repeat=3))

In [6]:
#does the lenght match
len(perm_ps) == 20**3

True

In [23]:
#make list of codes that has been used
codes = codebook[["Hyb1","Hyb2","Hyb3"]].values
code_set = [tuple(i) for i in codes]

In [32]:
#find difference
diff = list(set(perm_ps) - set(code_set))
len(diff)

4666

In [35]:
#get fake code with error correction
errorfakecode = []
for code in diff:
    error = (code[0]+code[1]-code[2]) % 20
    if error == 0:
        error = 20
    errorfakecode.append(error)

In [37]:
#make fakebook
fakecodes = pd.DataFrame(diff)
fakecodes.columns = ["Hyb1","Hyb2","Hyb3"]
fakecodes["Hyb4"] = errorfakecode

In [39]:
#make fake code names
fakegenes = []
for i in range(len(fakecodes)):
    fakegenes.append(f"fake{i}")

In [41]:
#add fake names
fakecodes.index = fakegenes

In [43]:
#add to codebook
codebook = pd.concat([codebook,fakecodes])

In [44]:
codebook

          Hyb1  Hyb2  Hyb3  Hyb4
Impact      17    16    13    20
Stxbp1      14    14     4     4
Sv2a        20     1     1    20
Mpped1       6    14     4    16
Pak3        14    19    13    20
Slc24a3     17    18     9     6
Fam126b     20    14     4    10
Sel1l       14     1     4    11
Sars         5     2     4     3
Sult4a1      8    12     4    16
Usp14       19    14     4     9
Idh3a        6    14    16     4
Pak1        13    16     9    20
Dmxl2       20    19    16     3
Usp34        2    18    16     4
Aplp2       10    16    13    13
Serinc3     16    16    10     2
Actr10       1    14     4    11
Eps15       20    16     2    14
Ctnnd2      12    20    13    19
Opcml        9     2    20    11
Metap2      20     5    10    15
Serf2       14    20    11     3
Trim9        9    10    19    20
Kcnb1       17     1    13     5
Gng3         5     9    10     4
Adcy1        2     8     4     6
Itfg1        5    20     9    16
Ap3b2        6    12    12     6
Arl8b        1    16     7    10
...        ...   ...   ...   ...
fake4636     7    11    19    19
fake4637     3    13    20    16
fake4638    15    18     2    11
fake4639    18     5    14     9
fake4640     9    16    18     7
fake4641    12    14    15    11
fake4642     6    15     1    20
fake4643    15     4    12     7
fake4644    12    20     4     8
fake4645    14    14     3     5
fake4646    17    20    17    20
fake4647    11    11     7    15
fake4648    14     3     4    13
fake4649    16     2     2    16
fake4650    10    11    14     7
fake4651    16     8    15     9
fake4652     1    14    10     5
fake4653    13     9    13     9
fake4654     9     2    13    18
fake4655     3     5     7     1
fake4656     7    19     6    20
fake4657     9    20     4     5
fake4658    18    13    11    20
fake4659    18    10    17    11
fake4660     8    12     2    18
fake4661     8     1     5     4
fake4662    17     5     8    14
fake4663     6    20    14    12
fake4664    14     6    14     6
fake4665    11    19    18    12

[8000 rows x 4 columns]

In [47]:
new_codebook = barcode_key_converter_within(codebook, num_hybs = 80, num_barcodes = 4, ch=1)

In [48]:
new_codebook.iloc[0].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [52]:
#write out new codebook
new_codebook.to_csv("codebook_string.csv")

In [31]:
JOB_ID=0
locations_path = glob.glob(f"/groups/CaiLab/personal/Lex/raw/Linus_10k_cleared_080918_NIH3T3/notebook_pyfiles/dots_comb/Channel_1/MMStack_Pos0/Threshold_{JOB_ID}/Dot_Locations/*")

In [32]:
locations_path

['/groups/CaiLab/personal/Lex/raw/Linus_10k_cleared_080918_NIH3T3/notebook_pyfiles/dots_comb/Channel_1/MMStack_Pos0/Threshold_0/Dot_Locations/locations_z_0.csv',
 '/groups/CaiLab/personal/Lex/raw/Linus_10k_cleared_080918_NIH3T3/notebook_pyfiles/dots_comb/Channel_1/MMStack_Pos0/Threshold_0/Dot_Locations/locations_z_1.csv']